---
working_dir: ./apps
auto_discover: true

auto_discover_opts:
  depth: 1
  delete: true

external_secrets:
  TRAEFIK_CF_DNS_API_TOKEN: op://Automation/Cloudflare API Token/password
  GARAGE_RPC_SECRET: op://Automation/Garage RPC Secret/password
  GARAGE_ADMIN_TOKEN: op://Automation/Garage Admin Token/password

---
name: bootstrap
working_dir: ./bootstrap
auto_discover: false
compose_files: ["compose.yaml"]
