---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Terragrunt CD
permissions: { contents: read }

on:
  workflow_dispatch: {}
  schedule: [{cron: '0 0 * * *'}] # Every day at midnight
  push:
    branches: ["main"]
    paths:
      - root.hcl
      - infrastructure/**
      - terraform/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  TG_NON_INTERACTIVE: "true"

jobs:
  apply:
    runs-on: infra-runners
    environment: TrueNAS
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup mise
        uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea # v4.2.1

      - name: Load Secrets
        uses: ./.github/actions/load-secrets
        with:
          op-connect-host: ${{ secrets.OP_CONNECT_HOST }}
          op-connect-token: ${{ secrets.OP_CONNECT_TOKEN }}

      - name: Terragrunt Init
        run: terragrunt run --all -- init -upgrade
        env:
          OP_CONNECT_HOST: ${{ secrets.OP_CONNECT_HOST }}
          OP_CONNECT_TOKEN: ${{ secrets.OP_CONNECT_TOKEN }}

      - name: Terragrunt Apply
        run: terragrunt run --all -- apply -auto-approve
        env:
          OP_CONNECT_HOST: ${{ secrets.OP_CONNECT_HOST }}
          OP_CONNECT_TOKEN: ${{ secrets.OP_CONNECT_TOKEN }}
